### PR TITLE
NO-ISSUE: Synchronize From Upstream Repositories

### PR DESCRIPTION
**Pull request by tmshort**
The staging/ and vendor/ directories have been synchronized from the upstream repositories, pulling in the following commits:

| Date | Commit | Author | Message |
| -    | -      | -      | -       |
|2024-06-05 00:03:09|[operator-framework/@2b11eb0](https://github.com/operator-framework//commit/2b11eb038d5d9c6b28fde21c56fd1d72456ae099)|dtfranz|UPSTREAM: <carry>: Add OpenShift specific files|
|2024-06-05 00:03:10|[operator-framework/@a011ec3](https://github.com/operator-framework//commit/a011ec32b2e67877b71dedf44ade24b2ac67406b)|Alexander Greene|UPSTREAM: <carry>: Drop commitchecker|
|2024-06-05 00:03:11|[operator-framework/@2c3ae14](https://github.com/operator-framework//commit/2c3ae140658c16d3fbd8de0cab2727815fdb02b0)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-operator-controller-container image to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/4022cd290f00a44d667dda03f2d78d84a488c7ed/images/ose-olm-operator-controller.yml|
|2024-06-05 00:03:12|[operator-framework/@67f6046](https://github.com/operator-framework//commit/67f60466e8b8b7c9c1a38e65f7d51cce416c8524)|Mikalai Radchuk|UPSTREAM: <carry>: update owners|
|2024-06-05 00:03:12|[operator-framework/@ca8f4eb](https://github.com/operator-framework//commit/ca8f4ebd95405ee9adf10bab8c4481a937bbd097)|Brett Tofel|UPSTREAM: <carry>: Add pointer to tooling README|
|2024-06-05 00:03:13|[operator-framework/@cbf4261](https://github.com/operator-framework//commit/cbf4261d902d7154ad363fc62c09fc022078d3af)|Mikalai Radchuk|UPSTREAM: <carry>: Disable Validating Admission Policy APIs downstream|
|2024-06-05 00:03:14|[operator-framework/@1e3b473](https://github.com/operator-framework//commit/1e3b473b9fc5d78721c4359ce1194805260d9cd9)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-operator-controller-container image to be consistent with ART for 4.16 Reconciling with https://github.com/openshift/ocp-build-data/tree/6250d54c4686a708ca5985afb73080e8ca9a1f7f/images/ose-olm-operator-controller.yml|
|2024-06-05 00:03:15|[operator-framework/@4877de2](https://github.com/operator-framework//commit/4877de213e0da9bf59157a275d2d644b7364294f)|Mikalai Radchuk|UPSTREAM: <carry>: Enable Validating Admission Policy APIs downstream|
|2024-06-05 00:03:16|[operator-framework/@9d0ffb4](https://github.com/operator-framework//commit/9d0ffb441c2f85cec1b64794093c8a11196a7303)|Ilias Rinis|UPSTREAM: <carry>: manifests: set required-scc for openshift workloads|
|2024-06-05 00:03:17|[operator-framework/@b8471ce](https://github.com/operator-framework//commit/b8471ce792673d65dcea8e36b44701f5371372a2)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-operator-controller-container image to be consistent with ART for 4.17 Reconciling with https://github.com/openshift/ocp-build-data/tree/4c1326094222f9209876f06833179a1b9178faf7/images/ose-olm-operator-controller.yml|

This pull request is expected to merge without any human intervention. If tests are failing here, changes must land upstream to fix any issues so that future downstreaming efforts succeed.

/cc @openshift/openshift-team-operator-runtime
/cc @openshift/openshift-team-operator-ecosystem

### CODE REVIEW

**Comment by grokspawn** [comment]
/lgtm
/approve

pending clean CI

**Comment by grokspawn** [comment]
/retitle OCPBUGS-34989: Synchronize From Upstream Repositories

**Comment by everettraven** [comment]
/retitle OCPBUGS-36582, OCPBUGS-34989: Synchronize From Upstream Repositories

**Comment by everettraven** [comment]
/retitle OCPBUGS-36582,OCPBUGS-34989: Synchronize From Upstream Repositories

**Pull request merged**
