### PR TITLE
OPRUN-3605: Update nodeSelector and tolerations on operator-controller deployment via kustomize patch

### PR DESCRIPTION
**Pull request by everettraven**
Updates the nodeSelector and toleration on the operator-controller deployment via a kustomize patch to allow it to be scheduled on the master node.

### CODE REVIEW

**Comment by grokspawn** [comment]
/retitle OPRUN-3605: Update nodeSelector and tolerations on operator-controller deployment via kustomize patch

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by joelanford** [comment]
/hold
waiting for manual payload job to complete successfully

/override ci/prow/openshift-e2e-aws-techpreview

**Pull request merged**
