### PR TITLE
OCPBUGS-36471: Synchronize From Upstream Repositories

### PR DESCRIPTION
**Pull request by tmshort**
The staging/ and vendor/ directories have been synchronized from the upstream repositories, pulling in the following commits:

| Date | Commit | Author | Message |
| -    | -      | -      | -       |
|2024-06-13 09:42:00|[operator-framework/@4607558](https://github.com/operator-framework//commit/460755827a69abcd438e12de36b4e1e2d7d851f5)|dtfranz|UPSTREAM: <carry>: Add OpenShift specific files|
|2024-06-13 09:42:01|[operator-framework/@7dbbe18](https://github.com/operator-framework//commit/7dbbe187b4a7e397966d4dec929e5d4b4ac94bb9)|Alexander Greene|UPSTREAM: <carry>: Drop commitchecker|
|2024-06-13 09:42:02|[operator-framework/@06a6297](https://github.com/operator-framework//commit/06a6297e4e46eb07ad6f1c39058eb83443f5d897)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-operator-controller-container image to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/4022cd290f00a44d667dda03f2d78d84a488c7ed/images/ose-olm-operator-controller.yml|
|2024-06-13 09:42:03|[operator-framework/@aac117e](https://github.com/operator-framework//commit/aac117e876537f6bd34116338e73eda8ecb962a0)|Mikalai Radchuk|UPSTREAM: <carry>: update owners|
|2024-06-13 09:42:04|[operator-framework/@628d91f](https://github.com/operator-framework//commit/628d91f1f5475025103e72b46a55de38449ce84c)|Brett Tofel|UPSTREAM: <carry>: Add pointer to tooling README|
|2024-06-13 09:42:05|[operator-framework/@b1bb801](https://github.com/operator-framework//commit/b1bb8011734222b8a50398514402166ff90ec540)|Mikalai Radchuk|UPSTREAM: <carry>: Disable Validating Admission Policy APIs downstream|
|2024-06-13 09:42:39|[operator-framework/@98482b9](https://github.com/operator-framework//commit/98482b96e82f3360d6bad12ac4578494225761c4)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-operator-controller-container image to be consistent with ART for 4.16 Reconciling with https://github.com/openshift/ocp-build-data/tree/6250d54c4686a708ca5985afb73080e8ca9a1f7f/images/ose-olm-operator-controller.yml|
|2024-06-13 09:42:40|[operator-framework/@c83bd37](https://github.com/operator-framework//commit/c83bd37507f455e7aefeb2fedf26d068da62a172)|Mikalai Radchuk|UPSTREAM: <carry>: Enable Validating Admission Policy APIs downstream|
|2024-06-13 09:42:41|[operator-framework/@63934a8](https://github.com/operator-framework//commit/63934a84e6e3d2725c0a7f53b7bc9c5004f7ae6c)|Ilias Rinis|UPSTREAM: <carry>: manifests: set required-scc for openshift workloads|
|2024-06-13 09:42:54|[operator-framework/@0aa6871](https://github.com/operator-framework//commit/0aa6871d3ad1bdcb577873b83f83067b8a70d147)|AOS Automation Release Team|UPSTREAM: <carry>: Updating ose-olm-operator-controller-container image to be consistent with ART for 4.17 Reconciling with https://github.com/openshift/ocp-build-data/tree/4c1326094222f9209876f06833179a1b9178faf7/images/ose-olm-operator-controller.yml|
|2024-06-18 20:17:58|[operator-framework/@91db550](https://github.com/operator-framework//commit/91db5507a8eb4429b42138a106b69b1f6a3b6540)|Todd Short|UPSTREAM: <carry>: Update generate-manifests to handle new directory|
|2024-06-24 18:53:30|[operator-framework/@3cbea6a](https://github.com/operator-framework//commit/3cbea6a4096045f4c82b48cade4a1ec1513ffa4a)|everettraven|UPSTREAM: <carry>: add everettraven to approvers+reviewers|

This pull request is expected to merge without any human intervention. If tests are failing here, changes must land upstream to fix any issues so that future downstreaming efforts succeed.

/cc @openshift/openshift-team-operator-runtime
/cc @openshift/openshift-team-operator-ecosystem

### CODE REVIEW

**Comment by m1kola** [comment]
/retitle OCPBUGS-36471: Synchronize From Upstream Repositories

**Comment by m1kola** [comment]
It looks like the e2e failure is legit:

```yaml
    lastState:
      terminated:
        containerID: cri-o://c5463b56a865a14a898781005fe54971974669beadbf67a5b9e071e471edb142
        exitCode: 1
        finishedAt: "2024-07-05T09:41:36Z"
        message: "2024-07-05T09:41:36Z\tINFO\tsetup\tstarting up the controller\t{\"version
          info\": \"version: \\\"1.22\\\", commit: \\\"389a7af4276443d614d11496b880424825fbb024\\\",
          date: \\\"2024-06-24T18:53:31Z\\\", state: \\\"dirty\\\"\"}\n2024-07-05T09:41:36Z\tINFO\tsetup\tset
          up manager\n2024-07-05T09:41:36Z\tERROR\tsetup\tunable to start manager\t{\"error\":
          \"failed to determine if *v1alpha1.ClusterCatalog is namespaced: failed
          to get restmapping: no matches for kind \\\"ClusterCatalog\\\" in group
          \\\"catalogd.operatorframework.io\\\"\"}\n"
        reason: Error
        startedAt: "2024-07-05T09:41:36Z"
```

**Comment by kuiwang02** [comment]
when I try to pre-verify this issue, I also met the issue mentioned at https://github.com/openshift/operator-framework-operator-controller/pull/114#issuecomment-2210596187

here is what I did:
```console
launch openshift/operator-framework-operator-controller#114,4.17 gcp
and then get cluster
kuiwang@kuiwang-mac jb % oc get clusterversion
NAME      VERSION                                                AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.17.0-0.test-2024-07-08-012639-ci-ln-wym0s6t-latest   True        False         11m     Cluster version is 4.17.0-0.test-2024-07-08-012639-ci-ln-wym0s6t-latest
kuiwang@kuiwang-mac jb % oc patch featuregate cluster -p '{"spec": {"featureSet": "TechPreviewNoUpgrade"}}' --type=merge
featuregate.config.openshift.io/cluster patched
kuiwang@kuiwang-mac jb % oc get clusterversion                                                                          
NAME      VERSION                                                AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.17.0-0.test-2024-07-08-012639-ci-ln-wym0s6t-latest   True        False         42m     Error while reconciling 4.17.0-0.test-2024-07-08-012639-ci-ln-wym0s6t-latest: the cluster operator olm is not available
kuiwang@kuiwang-mac jb % oc get co olm -o yaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  creationTimestamp: "2024-07-08T02:10:44Z"
  generation: 1
  name: olm
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: a4857d5c-396d-490d-92af-e70c1da0ea9a
  resourceVersion: "45180"
  uid: 3464604a-5218-4bbd-b43a-b47605f52082
spec: {}
status:
  conditions:
  - lastTransitionTime: "2024-07-08T02:11:11Z"
    message: All is well
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2024-07-08T02:11:10Z"
    message: 'OperatorcontrollerDeploymentOperatorControllerControllerManagerProgressing:
      Waiting for Deployment to deploy pods'
    reason: OperatorcontrollerDeploymentOperatorControllerControllerManager_Deploying
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-07-08T02:11:10Z"
    message: 'OperatorcontrollerDeploymentOperatorControllerControllerManagerAvailable:
      Waiting for Deployment'
    reason: OperatorcontrollerDeploymentOperatorControllerControllerManager_Deploying
    status: "False"
    type: Available
...
  versions:
  - name: operator
    version: 4.17.0-0.test-2024-07-08-012639-ci-ln-wym0s6t-latest
kuiwang@kuiwang-mac jb % oc get ns|grep operator-controller
openshift-operator-controller                      Active   31m
kuiwang@kuiwang-mac jb % oc -n openshift-operator-controller  get pod
NAME                                                      READY   STATUS             RESTARTS        AGE
operator-controller-controller-manager-784d877f7f-qhq9r   1/2     CrashLoopBackOff   9 (2m24s ago)   23m
kuiwang@kuiwang-mac jb % oc -n openshift-operator-controller  get pod operator-controller-controller-manager-784d877f7f-qhq9r -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.2.22/23"],"mac_address":"0a:58:0a:80:02:16","gateway_ips":["10.128.2.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.128.2.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.2.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.2.1"}],"ip_address":"10.128.2.22/23","gateway_ip":"10.128.2.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.22"
          ],
          "mac": "0a:58:0a:80:02:16",
          "default": true,
          "dns": {}
      }]
    kubectl.kubernetes.io/default-container: manager
    openshift.io/required-scc: restricted-v2
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-07-08T02:18:57Z"
  generateName: operator-controller-controller-manager-784d877f7f-
  labels:
    control-plane: controller-manager
    pod-template-hash: 784d877f7f
  name: operator-controller-controller-manager-784d877f7f-qhq9r
  namespace: openshift-operator-controller
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: operator-controller-controller-manager-784d877f7f
    uid: f8eac36a-2f80-4801-aee7-a99f4f4d604e
  resourceVersion: "58756"
  uid: 7f0c383a-e5b2-4c98-a0ec-86e7264fda85
...
  containerStatuses:
  - containerID: cri-o://9eaeea920f639f35cb817aa33cf2c2828a230edc38d8a01730eed0a70407eb9c
    image: registry.build02.ci.openshift.org/ci-ln-wym0s6t/stable@sha256:654a304b83015d22c49e5e72dcbe59fd9712355bfe38f35167aa481824b2ad69
    imageID: registry.build02.ci.openshift.org/ci-ln-wym0s6t/stable@sha256:654a304b83015d22c49e5e72dcbe59fd9712355bfe38f35167aa481824b2ad69
    lastState: {}
    name: kube-rbac-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-07-08T02:18:59Z"
  - containerID: cri-o://6fd9ef2e752c326df0cd97c9c56f4c03e77556637a7caf75d0ce79ae1a636453
    image: registry.build02.ci.openshift.org/ci-ln-wym0s6t/stable@sha256:167aa433488afa9aea6119b54eecf3a2f94cd1081b09aecf0dfe6f6a45097654
    imageID: registry.build02.ci.openshift.org/ci-ln-wym0s6t/stable@sha256:167aa433488afa9aea6119b54eecf3a2f94cd1081b09aecf0dfe6f6a45097654
    lastState:
      terminated:
        containerID: cri-o://6fd9ef2e752c326df0cd97c9c56f4c03e77556637a7caf75d0ce79ae1a636453
        exitCode: 1
        finishedAt: "2024-07-08T02:40:17Z"
        message: "2024-07-08T02:40:16Z\tINFO\tsetup\tstarting up the controller\t{\"version
          info\": \"version: \\\"1.22\\\", commit: \\\"389a7af4276443d614d11496b880424825fbb024\\\",
          date: \\\"2024-06-24T18:53:31Z\\\", state: \\\"dirty\\\"\"}\n2024-07-08T02:40:16Z\tINFO\tsetup\tset
          up manager\n2024-07-08T02:40:16Z\tERROR\tsetup\tunable to start manager\t{\"error\":
          \"failed to determine if *v1alpha1.ClusterCatalog is namespaced: failed
          to get restmapping: no matches for kind \\\"ClusterCatalog\\\" in group
          \\\"catalogd.operatorframework.io\\\"\"}\n"
        reason: Error
        startedAt: "2024-07-08T02:40:16Z"
    name: manager
    ready: false
    restartCount: 9
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=manager pod=operator-controller-controller-manager-784d877f7f-qhq9r_openshift-operator-controller(7f0c383a-e5b2-4c98-a0ec-86e7264fda85)
        reason: CrashLoopBackOff
  hostIP: 10.0.128.3
  hostIPs:
  - ip: 10.0.128.3
  phase: Running
  podIP: 10.128.2.22
  podIPs:
  - ip: 10.128.2.22
  qosClass: Burstable
  startTime: "2024-07-08T02:18:57Z"
kuiwang@kuiwang-mac jb % 
```

so, need to get it fixed before merging this PR.

**Comment by kuiwang02** [comment]
/hold
till the above is resolved.

Thanks

**Comment by kevinrizza** [comment]
/retitle OCPBUGS-36476,OCPBUGS-36471: Synchronize From Upstream Repositories

**Pull request merged**
