### PR TITLE
OPRUN-3075: Update to Upstream v0.7.0

### PR DESCRIPTION
**Pull request by dtfranz**

### CODE REVIEW

**Comment by grokspawn** [comment]
We have a couple of "UPSTREAM: <drop>" commits in here which only manipulate the downstream-only elements of the repo.  Is it intentional that on next sync we would drop them and generate 2 new ones (manifests + vendors)?

**Comment by dtfranz** [comment]
> We have a couple of "UPSTREAM: \<drop\>" commits in here which only manipulate the downstream-only elements of the repo. Is it intentional that on next sync we would drop them and generate 2 new ones (manifests + vendors)?

Yup! That's exactly what I did with the `<drop>` commits that were in the git history before.

**Pull request merged**
