### PR TITLE
[release-4.18] OCPBUGS-45114: combine bundle properties from csv and metadata/properties.yaml

### PR DESCRIPTION
**Pull request by dtfranz**
Manual cherry pick of [this commit](https://github.com/openshift/operator-framework-operator-controller/pull/199/commits/b9294a7b1839ec9dd02dcfc337e3a5fb7be30e78).

### CODE REVIEW

**Comment by Xia-Zhao-rh** [comment]
Test success, detail: https://issues.redhat.com/browse/OCPBUGS-45114

/label qe-approved
/label cherry-pick-approved
/lgtm

**Review by tmshort — APPROVED** [review]
/lgtm

**Pull request merged**
